config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show]
  
  root 'welcome#index'
  post :incoming, to: 'incoming#create'
  resources :topics do
    resources :bookmarks do
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy 
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :topics
  has_many :bookmarks
  has_many :likes, dependent: :destroy 
  
  
  def liked(bookmark)
     likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end
  
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
    authorize @bookmark
  end
  
  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.build(bookmark_params)
    current_user.bookmarks.push(@bookmark)
    authorize @bookmark
    if @bookmark.save
      redirect_to [@topic, @bookmark], notice: "bookmark was saved successfully."
    else
      flash[:error] = "Error saving topic, please try again"
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end
  
  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.update_attributes(bookmark_params)
      redirect_to [@topic, @bookmark], notice: "bookmark edit successfully"
    else
      flash[:error] = "Error editing bookmark, please try again"
      render :edit
    end
  end
  
  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted."
      redirect_to topics_path
    else
      flash[:error] = "Error deleting topic"
      render :show
    end
  end
  
  private
  
  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    # Take a look at these in your server logs
    # to get a sense of what you're dealing with.
    puts "INCOMING PARAMS HERE: #{params}"

    # You put the message-splitting and business
    # magic here. 
    
    # Find the user by using params[:sender]
    sender = params[:sender]
     # Find the topic by using params[:subject]
    subject = params[:subject]
     # Assign the url to a variable after retreiving it from params["body-plain"]
    url = params["body-plain"]

     # Check if user is nil, if so, create and save a new user
    @user = User.where(email: sender).first
    unless @user
      @user = User.new(email: sender, password: "helloworld")
      @user.skip_confirmation!
      @user.save
    end
     # Check if the topic is nil, if so, create and save a new topic
    @topic = Topic.where(title: subject).first
    if @topic
      
    else
      @topic = Topic.new(title: subject, user:@user)
      @topic.save
    end
     # Now that you're sure you have a valid user and topic, build and save a new bookmark
    @bookmark = Bookmark.new(url: url, topic: @topic)
    @bookmark.save
    # Assuming all went well. 
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new 
  end
  
    def create
     @bookmark = Bookmark.find(params[:bookmark_id])
     like = current_user.likes.build(bookmark: @bookmark)
 
     if like.save
       redirect_to [@bookmark.topic, @bookmark], notice: "bookmark was liked."
     else
       redirect_to [@bookmark.topic, @bookmark], notice: "error, please try again."
     end
   end

   def destroy
     @bookmark = Bookmark.find(params[:bookmark_id])
     like = current_user.liked(@bookmark)
 
     if like.destroy
       redirect_to [@bookmark.topic, @bookmark], notice: "bookmark was unliked."
     else
       redirect_to [@bookmark.topic, @bookmark], notice: "error, please try again."
     end
   end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    if current_user
      @topics = current_user.topics
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
    authorize @topic
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    authorize @topic
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "Error saving topic, please try again"
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end
  
  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      redirect_to @topic, notice: "Topic was updtaed"
    else
      flash[:error] = "Error editing topic, please try again"
      render :edit
    end
  end
  
  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted."
      redirect_to topics_path
    else
      flash[:error] = "Error deleting topic"
      render :show
    end
  end
  
  private
  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    #@topics = current_user.topics
    @bookmarks = current_user.bookmarks
    @liked_bookmarks = Like.where(user_id: current_user.id).to_a
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @topics = Topic.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmark.html.erb
<% thumbBookmark = LinkThumbnailer.generate(bookmark.url) %>
  <div class="img-thumbnail" width="304" height="236">
    <%= link_to (image_tag thumbBookmark.images.first.src, size: "200x200"),  topic_bookmark_path(bookmark.topic, bookmark)%>
    <p class="text-center"> <%= link_to "click to enter this site", bookmark.url %> </p>
    <%= render partial: 'likes/like', locals: { topic: bookmark.topic, bookmark: bookmark } %>
  </div>

app/views/bookmarks/_form.html.erb
<%= form_for [topic, bookmark] do |f| %>
  <div class="form-group">
    <%= f.label :URL %>
    <%= f.text_field :url, class: "form-control", placeholder: "Enter a url for this bookmark" %>
  </div>
  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit a Bookmark</h1>
<div class="row">
  <div class="col-md-4">
    <p> Edit Bookmark </p>
  </div>
  
  <div class="col-md-8">
    <%= render partial: 'form', locals: {topic: @topic, bookmark: @bookmark} %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<h1>Create new Bookmark</h1>
<div class="row">
  <div class="col-md-4">
    <p> Create new Bookmark </p>
  </div>
  
  <div class="col-md-8">
    <%= render partial: 'form', locals: {topic: @topic, bookmark: @bookmark} %>
  </div>
</div>

app/views/bookmarks/show.html.erb
<% thumbBookmark = LinkThumbnailer.generate(@bookmark.url) %>
<h1>
  Bookmarks#information
  <% if policy(@bookmark).edit? %>
    <%= link_to "Edit", edit_topic_bookmark_path(@topic, @bookmark), class: 'btn btn-success'%>
    <%= link_to "Delete", [@topic, @bookmark], method: :delete, class: 'btn btn-danger', data:{confirm: "Are you sure to delete this topic?"} %>
  <% end %>
  <%= render partial: 'likes/like', locals: { topic: @bookmark.topic, bookmark: @bookmark } %>
</h1>
<div class="row">
  <div class="col-md-4">
    <%= image_tag thumbBookmark.images.first.src, size: "200x200"%>
  </div>
  <h2> <%= thumbBookmark.title %></h2>
  <div class="col-md-4">
    <p> URL </p>
    <%= link_to @bookmark.url, @bookmark.url %>
  </div>
  <div class="col-md-4">
    <p> Description </p>
    <%= thumbBookmark.description %>
  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs"> 
      <li><%= link_to "Blocmarks", root_path %> </li>
      
      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= link_to current_user.name || current_user.email, current_user%>!
            <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
              <span class="glyphicon glyphicon-user"></span>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
              <span class="glyphicon glyphicon-log-out"></span>
            <% end %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>

    </ul>
  
       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
    
<%= yield %>
  </div>
</body>
</html>

app/views/likes/_like.html.erb
<div class="text-center">
  <% if policy(Like.new).create? %>
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [topic,bookmark, like], class: 'btn btn-danger', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
      <% end %>
    <% else %>
      <%= link_to [topic, bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter a title for topic" %>
  </div>
  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<div class="row">
  <div class="col-md-4">
    <p> Edit Topic Title</p>
  </div>
  
  <div class="col-md-8">
    <%= render partial: 'form', locals: {topic: @topic} %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>All Blocmarks</h1>
<% if @topics %>
  <% @topics.each do |topic| %>
    <p> <%= link_to "##{topic.title}", topic %> </p>
      <%= render topic.bookmarks %>
  <% end %>
<% end %>
<br>
<p class="text-center"> 
  <% if current_user %>
  <%= link_to "Create new topic", new_topic_path, class: 'btn btn-success'%>
  <% end %>
</p>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<div class="row">
  <div class="col-md-4">
    <p> Create New Topic for Bookmarks </p>
  </div>
  
  <div class="col-md-8">
    <%= render partial: 'form', locals: {topic: @topic} %>
  </div>
</div>

app/views/topics/show.html.erb
<h1>
  <%= @topic.title %> 
  <% if policy(@topic).edit? %>
    <%= link_to "Edit", edit_topic_path, class: "btn btn-success" %>
    <%= link_to "Delete", @topic, method: :delete, class: "btn btn-danger", data:{confirm: "Are you sure to delete this topic?"} %>
  <% end %>
</h1>
<%= render @topic.bookmarks %>
<% if policy(Bookmark.new).create? %>
  <p class="text-center"> <%= link_to "Create new Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %> </p>
<% end %>

app/views/users/show.html.erb
<h1 class="text-center">My Blocmarks</h1>
<div class="row">
<% @bookmarks.each do |bookmark| %>
  <div class="col-md-4">
  <% thumbBookmark = LinkThumbnailer.generate(bookmark.url) %>
  <div class="img-thumbnail" width="304" height="236">
    <%= link_to (image_tag thumbBookmark.images.first.src, size: "200x200"),  topic_bookmark_path(bookmark.topic, bookmark)%>
    <p class="text-center"> <%= link_to "click to enter this site", bookmark.url %> </p>
  </div>
    <p class="text-center"> <%= link_to "remove", topic_bookmark_path(bookmark.topic, bookmark), method: :delete %> </p>
  </div>
<% end %>
</div>

<h1 class="text-center"> Liked Blocmarks </h1>
<div class="row">
  <% @liked_bookmarks.each do |like| %>
  <%=render partial:"bookmarks/bookmark", locals: {bookmark: like.bookmark}%>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1 class="text-center"> All Blocmarks </h1>
<% if @topics %>
  <% @topics.each do |topic| %>
    <p> <%= link_to "##{topic.title}", topic %> </p>
      <%= render topic.bookmarks %>
  <% end %>
<% end %>
<br>
<p class="text-center"> 
  <% if current_user %>
  <%= link_to "Create new topic", new_topic_path, class: 'btn btn-success'%>
  <% end %>
</p>